options:
  capwap_AC_port:
    type: string
    default: "1200"
    description: "A port for capwap AC server"
  openflow_port:
    type: string
    default: "6653"
    description: "A port for openflow server"
  netconf_datastore_path:
    type: string
    default: "/usr/bin/transAPI/"
    description: "A path for data modules of Netconf server"


